#
# As docker is used the standard port of 8080 is sufficient.
# The docker call must include it via 'docker run -p 1234:8080' (external port:internal port)
#
spring:
  thymeleaf.cache: false
logging:
  level:
    ROOT: INFO
    org.springframework.web: INFO
    guru.springframework.controllers: INFO
    org.hibernate: INFO
    com.inidus.platform: INFO
#
# THESE PROPERTIES MUST BE SET!
# As docker is used this can be done via passing environment variables into docker when starting the image.
# Ideally a .env file is being used, eg:
#
# # CDR
# cdr-connector.url=http://178.62.71.220:8080
# cdr-connector.isTokenAuth=TRUE
# cdr-connector.username=guest
# cdr-connector.password=guest
#
# The docker call then includes it via 'docker run --env-file "fhir-adaptor.env"'
#
cdr-connector:
  url:
  username:
  password:
  is-token-auth: